language: ruby

git:
  depth: 10

cache: bundler

rvm:
  - 2.2
  - 2.1
  - 2.0

branches:
  only:
    - master

before_install:
  - gem update --system

install:
  - gem install bundler --no-ri --no-rdoc
  - bundle install

script:
  - bundle exec jekyll clean
  - bundle exec jekyll build
  - bundle exec jekyll serve
