# Site settings...
title: Komunitas Git Indonesia
description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis distinctio sit nostrum incidunt, aspernatur earum, id ipsa fuga voluptate? Ducimus minus.
baseurl: ""
url: "https://gitindonesia.github.io"
twitter_username: Git_ID
facebook_username: GitHubID
disqus_shortname: githubid
github:
  username: GitIndonesia
  repo: GitIndonesia/GitIndonesia.github.io

# Build settings...
sass:
  style: compressed
encoding: "utf-8"
markdown: kramdown
permalink: /blog/:title/
timezone: Asia/Jakarta

# Exclude system files...
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Default value Front Matter...
defaults:
  - # default post type
    scope:
      type: "posts"
    values:
      layout: "post"
      comment: true
