# Site settings
title: "Github - Indonesia"
email: 
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://github-id.org/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://octodex.github.com/images/dojocat.jpg"
disqus_account: Github Indonesia 
github_repository: https://github.com/GitHubIndonesia/githubindonesia.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  Github Indonesia
linkedin_link: 
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://www.facebook.com/groups/GitHubID/?fref=ts\">Github - Indonesia</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/GitHubIndonesia/githubindonesia.github.io\">Repository</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
